export enum UserRole {
  USER = 'USER',
  MERCHANT = 'MERCHANT',
  ADMIN = 'ADMIN',
  CREDIT_OFFICER = 'CREDIT_OFFICER',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
}