packages:
  - 'apps/*'
  - 'libs/*'
  - '!**/node_modules/**'
  - '!**/build/**'
  - '!**/dist/**'
  - '!**/android/**'
  - '!**/ios/**'
  - '!**/coverage/**'
  - '!**/.next/**'
  - '!**/.nx/**'
  - '!**/tools/**'
  - '!**/governance/**'
