@echo off
REM Clear Prisma environment variables
set PRISMA_MIGRATION_ENGINE_BINARY=
set PRISMA_SCHEMA_ENGINE_BINARY=
set PRISMA_QUERY_ENGINE_BINARY=
set PRISMA_INTROSPECTION_ENGINE_BINARY=
set PRISMA_CLI_BINARY_TARGETS=

REM Run the build
pnpm build
