version: '3.8'

services:
  postgres_test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: meqenet_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:7-alpine
    ports:
      - '6380:6379'

  api_gateway:
    build:
      context: .
      dockerfile: backend/services/api-gateway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - auth_service
      - payments_service

  auth_service:
    build:
      context: .
      dockerfile: backend/services/auth-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://testuser:testpassword@postgres_test:5432/meqenet_test
      REDIS_HOST: redis_test
    depends_on:
      - postgres_test
      - redis_test

  payments_service:
    build:
      context: .
      dockerfile: backend/services/payments-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://testuser:testpassword@postgres_test:5432/meqenet_test
    depends_on:
      - postgres_test

volumes:
  postgres_test_data: