receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # Exporter for OpenSearch (for logs)
  opensearch:
    hosts: ["http://opensearch:9200"]
    index: "meqenet-logs"

  # Exporter for Jaeger (for traces)
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  # Exporter for Prometheus (for metrics)
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Exporter for logging to the console (for debugging)
  logging:
    verbosity: detailed

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch, logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
