packages:
  # The root backend application, which may contain shared logic.
  - "backend"
  # All individual microservices located under the backend/services/ directory.
  - "backend/services/*"
  # The root frontend application
  - "frontend"
  - "frontend/apps/*"
  - "frontend/libs/*"
  # Tools
  - "tools/*"
  # Exclusions to prevent duplicate packages and improve performance
  - "!**/node_modules/**"
  - "!**/build/**"
  - "!**/dist/**"
  - "!**/coverage/**"
  - "!**/reports/**"
  - "!**/.git/**"
  - "!**/logs/**"
  - "!**/tmp/**"
  - "!**/temp/**"
  - "!**/cache/**"
  - "!**/android/**"
  - "!**/ios/**"
  - "!**/.next/**"
  - "!**/.nx/**"
  - "!**/governance/**"
