packages:
  # The root backend application, which may contain shared logic.
  - "backend"
  # All individual microservices located under the backend/services/ directory.
  - "backend/services/*"
  # The root frontend application
  - "frontend"
  - "frontend/apps/*"
