apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: OpenSearch
    type: opensearch
    access: proxy
    url: http://opensearch:9200
    jsonData:
      database: "meqenet-logs"
      timeField: "@timestamp"
