export enum NotificationType {
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_LATE = 'PAYMENT_LATE',
  CREDIT_LIMIT_UPDATED = 'CREDIT_LIMIT_UPDATED',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
  SECURITY_ALERT = 'SECURITY_ALERT',
  PROMOTIONAL = 'PROMOTIONAL',
  SYSTEM = 'SYSTEM',
  GENERAL_NOTIFICATION = 'GENERAL_NOTIFICATION',
  PAYMENT_PLAN_CREATED = 'PAYMENT_PLAN_CREATED',
}













