name: Backend CI

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "backend/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/backend-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Enable corepack
        run: corepack enable

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: "monitor"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: typescript

      - name: Build backend
        run: pnpm build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Validate Mermaid diagrams
        uses: jgreywolf/docs-mermaid-validate-action@v1

  api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ReDocly API Docs
        uses: redocly/cli-action@v1
        with:
          command: "build-docs backend/openapi.yaml"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-docs
          path: redoc-static.html

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run E2E tests
        run: bash scripts/run-e2e-tests.sh
