name: 🏦 Compliance Validation Suite

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  NODE_VERSION: "22"
  PNPM_VERSION: "10.4.1"

permissions:
  contents: read

jobs:
  pci-dss:
    name: 💳 PCI-DSS Level 1 Compliance
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: 📦 Install pnpm (with retry logic)
        run: |
          echo "📦 Installing pnpm with retry logic..."
          for i in {1..3}; do
            if npm install -g pnpm@${{ env.PNPM_VERSION }}; then
              echo "✅ pnpm installed successfully on attempt $i"
              break
            else
              echo "❌ pnpm installation failed on attempt $i"
              if [ $i -eq 3 ]; then
                echo "🔄 Falling back to direct download..."
                curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=${{ env.PNPM_VERSION }} sh -
                break
              fi
              sleep 2
            fi
          done

          # Verify pnpm installation
          pnpm --version
      - run: pnpm install --no-frozen-lockfile
      - name: Run PCI Checks
        run: |
          echo "Validating encryption, key rotation, and network isolation policies..."
          echo "✅ PCI-DSS checks placeholder (extend with concrete tests)."

  sox:
    name: 🧾 SOX IT General Controls
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: 📦 Install pnpm (with retry logic)
        run: |
          echo "📦 Installing pnpm with retry logic..."
          for i in {1..3}; do
            if npm install -g pnpm@${{ env.PNPM_VERSION }}; then
              echo "✅ pnpm installed successfully on attempt $i"
              break
            else
              echo "❌ pnpm installation failed on attempt $i"
              if [ $i -eq 3 ]; then
                echo "🔄 Falling back to direct download..."
                curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=${{ env.PNPM_VERSION }} sh -
                break
              fi
              sleep 2
            fi
          done

          # Verify pnpm installation
          pnpm --version
      - run: pnpm install --no-frozen-lockfile
      - name: Run SOX Checks
        run: echo "✅ SOX controls placeholder (change management, access reviews)."

  iso27001:
    name: 🔐 ISO 27001 Controls
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: 📦 Install pnpm (with retry logic)
        run: |
          echo "📦 Installing pnpm with retry logic..."
          for i in {1..3}; do
            if npm install -g pnpm@${{ env.PNPM_VERSION }}; then
              echo "✅ pnpm installed successfully on attempt $i"
              break
            else
              echo "❌ pnpm installation failed on attempt $i"
              if [ $i -eq 3 ]; then
                echo "🔄 Falling back to direct download..."
                curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=${{ env.PNPM_VERSION }} sh -
                break
              fi
              sleep 2
            fi
          done

          # Verify pnpm installation
          pnpm --version
      - run: pnpm install --no-frozen-lockfile
      - name: Run ISO 27001 Checks
        run: echo "✅ ISO 27001 controls placeholder (risk assessment, logs)."
