name: 🛡️ Compliance Evidence Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1" # Run at 2 AM UTC every Monday
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gather-evidence:
    name: "Gather Compliance Evidence"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Install yq"
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
        shell: bash

      - name: "Make script executable"
        run: chmod +x scripts/gather-compliance-evidence.sh

      - name: "Run Evidence Gathering Script"
        run: ./scripts/gather-compliance-evidence.sh

      - name: "Upload Compliance Report"
        uses: actions/upload-artifact@v4
        with:
          name: compliance-report
          path: dist/compliance_evidence/compliance-report.md
