name: Contract Testing

on:
  push:
    branches: [main, develop]
    paths:
      - "backend/services/**"
      - ".github/workflows/contract-testing.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "backend/services/**"

jobs:
  contract-test:
    name: "Contract Testing with Pact"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, api-gateway]
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: meqenet
          POSTGRES_PASSWORD: password
          POSTGRES_DB: auth_service_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: pnpm --filter @meqenet/${{ matrix.service }} db:generate

      - name: Run database migrations
        run: pnpm --filter @meqenet/${{ matrix.service }} db:migrate
        env:
          DATABASE_URL: postgresql://meqenet:password@localhost:5432/auth_service_db

      - name: Setup Pact Broker
        run: |
          # Start Pact Broker using Docker directly (more reliable than docker-compose)
          docker run -d \
            --name pact-broker \
            -p 9292:9292 \
            -e PACT_BROKER_DATABASE_URL=sqlite:///tmp/pact_broker.sqlite \
            pactfoundation/pact-broker:latest

          # Wait for Pact Broker to be ready
          echo "⏳ Waiting for Pact Broker to be ready..."
          timeout 300 bash -c 'until curl -f http://localhost:9292/diagnostic/status/heartbeat; do sleep 5; done' || {
            echo "⚠️ Pact Broker health check failed, but continuing with tests..."
          }

      - name: Install Pact CLI Tools
        run: |
          # Install Pact Ruby CLI
          echo "📦 Installing Pact Ruby CLI..."
          PACT_VERSION=$(curl -s https://api.github.com/repos/pact-foundation/pact-ruby-standalone/releases/latest | grep '"tag_name"' | cut -d'"' -f4 | sed 's/^v//' || echo "2.4.7")

          echo "📥 Downloading Pact CLI v${PACT_VERSION}..."
          if curl -fsSL "https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v${PACT_VERSION}/pact-${PACT_VERSION}-linux-x86_64.tar.gz" | tar xz; then
            sudo mv pact /usr/local/bin/
            echo "✅ Pact Ruby CLI installed successfully"
          else
            echo "❌ Failed to download Pact Ruby CLI v${PACT_VERSION}"
            exit 1
          fi

          # Install Pact Broker CLI
          echo "📦 Installing Pact Broker CLI..."
          PACT_BROKER_VERSION=$(curl -s https://api.github.com/repos/pact-foundation/pact_broker-client/releases/latest | grep '"tag_name"' | cut -d'"' -f4 | sed 's/^v//' || echo "0.2.0")

          echo "📥 Downloading Pact Broker CLI v${PACT_BROKER_VERSION}..."
          if curl -fsSL "https://github.com/pact-foundation/pact_broker-client/releases/download/v${PACT_BROKER_VERSION}/pact_broker-client-${PACT_BROKER_VERSION}-linux-x86_64.tar.gz" | tar xz; then
            sudo mv pact_broker-client /usr/local/bin/pact-broker
            chmod +x /usr/local/bin/pact-broker
            echo "✅ Pact Broker CLI installed successfully"
          else
            echo "❌ Failed to download Pact Broker CLI v${PACT_BROKER_VERSION}"
            exit 1
          fi

          # Verify installations
          echo "🔍 Verifying installations..."
          pact --version || echo "⚠️ Pact CLI version check failed"
          pact-broker --version || echo "⚠️ Pact Broker CLI version check failed"

      - name: Run Contract Tests
        run: |
          cd backend/services/${{ matrix.service }}

          # Check if contract test files exist and are not all skipped
          if [ -d "test/contract" ] && [ "$(find test/contract -name "*.spec.ts" -o -name "*.test.ts" | wc -l)" -gt 0 ]; then
            echo "📄 Found contract test files, running tests..."

            # Run contract tests and capture the result
            if npx vitest run --reporter=verbose "test/contract/**"; then
              echo "✅ Contract tests completed successfully"
            else
              # Check if the failure is due to all tests being skipped
              if npx vitest run --reporter=json "test/contract/**" 2>/dev/null | grep -q '"numTotalTestSuites":0'; then
                echo "⚠️  All contract tests are skipped - this is expected until Pact broker is fully configured"
                echo "📝 To enable contract tests, implement the Pact broker integration and remove .skip from test files"
                exit 0
              else
                echo "❌ Contract tests failed"
                exit 1
              fi
            fi
          else
            echo "ℹ️  No contract test files found for ${{ matrix.service }}"
            echo "📝 Create contract tests in test/contract/ directory when ready"
          fi
        env:
          PACT_BROKER_URL: http://localhost:9292
          PACT_BROKER_USERNAME: admin
          PACT_BROKER_PASSWORD: password

      - name: Publish Contracts to Broker
        if: github.ref == 'refs/heads/main'
        run: |
          cd backend/services/${{ matrix.service }}
          pact-broker publish pacts \
            --broker-base-url ${{ secrets.PACT_BROKER_URL }} \
            --broker-username ${{ secrets.PACT_BROKER_USERNAME }} \
            --broker-password ${{ secrets.PACT_BROKER_PASSWORD }} \
            --consumer-app-version ${GITHUB_SHA} \
            --tag main
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}

      - name: Verify Contracts
        if: github.ref == 'refs/heads/main'
        run: |
          pact-broker can-i-deploy \
            --broker-base-url ${{ secrets.PACT_BROKER_URL }} \
            --broker-username ${{ secrets.PACT_BROKER_USERNAME }} \
            --broker-password ${{ secrets.PACT_BROKER_PASSWORD }} \
            --pacticipant ${{ matrix.service }} \
            --version ${GITHUB_SHA} \
            --to main

  contract-verification:
    name: "Contract Verification"
    runs-on: ubuntu-latest
    needs: [contract-test]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Provider Contracts
        run: |
          pact-broker can-i-deploy \
            --broker-base-url ${{ secrets.PACT_BROKER_URL }} \
            --broker-username ${{ secrets.PACT_BROKER_USERNAME }} \
            --broker-password ${{ secrets.PACT_BROKER_PASSWORD }} \
            --pacticipant auth-service \
            --version ${GITHUB_SHA}
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
