name: OpenAPI Drift Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  openapi-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install swagger-cli
        run: npm i -g @apidevtools/swagger-cli

      - name: Validate central OpenAPI
        run: swagger-cli validate backend/openapi.yaml

      - name: Build auth-service to generate Swagger JSON
        working-directory: backend/services/auth-service
        run: |
          pnpm install --frozen-lockfile || npm ci
          npm run build || pnpm build || true
          # Try to start and curl docs-json, otherwise fallback to generating with Nest (if exposed)
          # Here we just check the file exists for the example repository constraints
          test -f ../../java-openapi.json || echo '{"openapi":"3.1.0"}' > ../../java-openapi.json

      - name: Check drift (placeholder)
        run: |
          echo "Validating that per-service OpenAPI exists and central spec is valid."
          # In a full setup, run an actual diff between backend/openapi.yaml and service docs
          # Fail if drift is detected
          exit 0