# 🎯 Meqenet.et Enterprise Governance Configuration
# C-Suite Dashboard Configuration for Ethiopian FinTech Platform

dashboards:
  # Chief Executive Officer - Strategic Business Intelligence
  ceo:
    enabled: true
    name: CEO Strategic Dashboard
    description: Strategic Business Intelligence & Executive Oversight
    script_path: dashboards/ceo.py
    schedule_cron: "0 8 * * 1-5" # 8 AM weekdays
    timeout_minutes: 15
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: ceo
      COMPLIANCE_LEVEL: enterprise

  # Chief Financial Officer - Financial Performance & Risk
  cfo:
    enabled: true
    name: CFO Financial Dashboard
    description: Financial Performance & Budget Analytics
    script_path: dashboards/cfo.py
    schedule_cron: "0 9 * * 1-5" # 9 AM weekdays
    timeout_minutes: 12
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: cfo
      COMPLIANCE_LEVEL: enterprise

  # Chief Technology Officer - Technical Infrastructure
  cto:
    enabled: true
    name: CTO Technical Dashboard
    description: Technical Infrastructure & DevOps Metrics
    script_path: dashboards/cto.py
    schedule_cron: "*/30 * * * *" # Every 30 minutes
    timeout_minutes: 10
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: cto
      COMPLIANCE_LEVEL: enterprise

  # Chief Compliance Officer - Regulatory Compliance
  cco:
    enabled: true
    name: CCO Compliance Dashboard
    description: Regulatory Compliance & Risk Management
    script_path: dashboards/cco.py
    schedule_cron: "0 */2 * * *" # Every 2 hours
    timeout_minutes: 8
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: cco
      COMPLIANCE_LEVEL: enterprise

  # Chief Information Security Officer - Security Posture
  ciso:
    enabled: true
    name: CISO Security Dashboard
    description: Security Posture & Threat Intelligence
    script_path: dashboards/ciso.py
    schedule_cron: "*/15 * * * *" # Every 15 minutes
    timeout_minutes: 6
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: ciso
      COMPLIANCE_LEVEL: enterprise

# Multi-Channel Notification System
notifications:
  enabled: true
  email:
    enabled: true
    smtp_server: smtp.gmail.com
    smtp_port: 587
    username: governance@meqenet.et
    password: "${GOVERNANCE_EMAIL_PASSWORD}"
    recipients:
      ceo: ["ceo@meqenet.et"]
      cfo: ["cfo@meqenet.et"]
      cto: ["cto@meqenet.et"]
      cco: ["cco@meqenet.et"]
      ciso: ["ciso@meqenet.et"]
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channels:
      general: "#governance-alerts"
      security: "#security-incidents"
  teams:
    enabled: true
    webhook_url: "${TEAMS_WEBHOOK_URL}"

# Backup Configuration
backup:
  enabled: true
  schedule_cron: "0 2 * * *" # Daily at 2 AM
  retention_days: 30
  max_backups: 10
  include_logs: true
  include_reports: true
  include_databases: true

# Monitoring Configuration
monitoring:
  enabled: true
  health_check_interval: 300 # 5 minutes
  performance_thresholds:
    max_execution_time: 1800
    max_memory_usage: 2048
    max_cpu_usage: 80
  metrics_retention: 30

# Compliance Frameworks
compliance:
  enabled: true
  frameworks:
    nbe: true # National Bank of Ethiopia
    gdpr: true # General Data Protection Regulation
    pci_dss: true # Payment Card Industry
    iso27001: true # Information Security Management
    soc2: true # Service Organization Control

# Platform Information
platform:
  system: Windows
  architecture: 64bit
  python_version: "3.11"
  environment: enterprise

# Version Information
version: "2.0.0"
last_updated: "2025-09-03"
description: "Enterprise governance configuration for Meqenet.et"
