# 🎯 Meqenet.et Enterprise Governance Configuration - FinTech Edition
# Enterprise-Grade C-Suite Dashboard Configuration for Ethiopian FinTech Platform
# Compliance: NBE, GDPR, PCI-DSS, ISO27001, SOC2

# Executive Dashboard Configuration
dashboards:
  # Chief Executive Officer - Strategic Business Intelligence
  ceo:
    enabled: true
    name: CEO Strategic Dashboard
    description: Strategic Business Intelligence & Executive Oversight
    script_path: governance/dashboards/ceo.py
    schedule_cron: "0 8 * * 1-5" # Business hours, weekdays
    timeout_minutes: 15
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: ceo
      COMPLIANCE_LEVEL: enterprise
      REPORT_FORMAT: executive_summary
    business_hours_only: true
    critical_thresholds:
      revenue_drop: 0.05 # 5% revenue drop triggers alert
      customer_churn: 0.03 # 3% churn rate triggers alert

  # Chief Financial Officer - Financial Performance & Risk
  cfo:
    enabled: true
    name: CFO Financial Dashboard
    description: Financial Performance & Budget Analytics
    script_path: governance/dashboards/cfo.py
    schedule_cron: "0 9 * * 1-5" # Business hours, weekdays
    timeout_minutes: 12
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: cfo
      COMPLIANCE_LEVEL: enterprise
      REPORT_FORMAT: financial_summary
      CURRENCY: ETB
    business_hours_only: true
    critical_thresholds:
      burn_rate_threshold: 0.8 # 80% of monthly budget
      cash_runway_days: 90 # Alert when below 90 days

  # Chief Technology Officer - Technical Infrastructure
  cto:
    enabled: true
    name: CTO Technical Dashboard
    description: Technical Infrastructure & DevOps Metrics
    script_path: governance/dashboards/cto.py
    schedule_cron: "*/30 * * * *" # Every 30 minutes
    timeout_minutes: 10
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: cto
      COMPLIANCE_LEVEL: enterprise
      MONITORING_LEVEL: comprehensive
    business_hours_only: false
    critical_thresholds:
      system_uptime: 0.995 # 99.5% uptime required
      response_time_ms: 2000 # Max 2s response time
      error_rate: 0.001 # Max 0.1% error rate

  # Chief Compliance Officer - Regulatory Compliance
  cco:
    enabled: true
    name: CCO Compliance Dashboard
    description: Regulatory Compliance & Risk Management
    script_path: governance/dashboards/cco.py
    schedule_cron: "0 */2 * * *" # Every 2 hours
    timeout_minutes: 8
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: cco
      COMPLIANCE_LEVEL: enterprise
      REGULATORY_FRAMEWORK: nbe_gdpr_pci
      REPORT_FORMAT: compliance_audit
    business_hours_only: false
    critical_thresholds:
      compliance_score: 0.95 # Min 95% compliance score
      audit_findings: 5 # Max 5 open audit findings
      risk_score: 3.0 # Max risk score threshold

  # Chief Information Security Officer - Security Posture
  ciso:
    enabled: true
    name: CISO Security Dashboard
    description: Security Posture & Threat Intelligence
    script_path: governance/dashboards/ciso.py
    schedule_cron: "*/15 * * * *" # Every 15 minutes
    timeout_minutes: 6
    dependencies: []
    environment_vars:
      DASHBOARD_TYPE: ciso
      COMPLIANCE_LEVEL: enterprise
      SECURITY_LEVEL: maximum
      THREAT_INTELLIGENCE: enabled
    business_hours_only: false
    critical_thresholds:
      security_score: 0.90 # Min 90% security score
      vulnerability_count: 10 # Max 10 critical vulnerabilities
      incident_response_time: 3600 # Max 1 hour response time

# Multi-Channel Notification System
notifications:
  enabled: true

  # Email Notifications (Primary Communication Channel)
  email:
    enabled: true
    smtp_server: smtp.gmail.com
    smtp_port: 587
    smtp_security: tls
    username: governance@meqenet.et
    password: "${GOVERNANCE_EMAIL_PASSWORD}" # Environment variable
    recipients:
      ceo: ["ceo@meqenet.et"]
      cfo: ["cfo@meqenet.et"]
      cto: ["cto@meqenet.et"]
      cco: ["cco@meqenet.et"]
      ciso: ["ciso@meqenet.et"]
      board: ["board@meqenet.et"]
      security_team: ["security@meqenet.et"]
    templates:
      critical_alert: templates/email/critical_alert.html
      executive_summary: templates/email/executive_summary.html
      compliance_report: templates/email/compliance_report.html

  # Slack Integration (Real-time Team Communication)
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channels:
      general: "#governance-alerts"
      security: "#security-incidents"
      compliance: "#compliance-updates"
      executive: "#executive-summary"
    username: "Meqenet Governance Suite"
    icon_emoji: ":chart_with_upwards_trend:"
    rate_limit: 30 # Max messages per hour

  # Microsoft Teams Integration (Enterprise Communication)
  teams:
    enabled: true
    webhook_url: "${TEAMS_WEBHOOK_URL}"
    channels:
      governance: "governance-updates"
      security: "security-alerts"
      executive: "executive-dashboard"
    rate_limit: 50 # Max messages per hour

  # Alert Levels and Escalation
  alert_levels:
    info:
      enabled: true
      channels: ["slack"]
      escalation_time: 0
    warning:
      enabled: true
      channels: ["slack", "email"]
      escalation_time: 300 # 5 minutes
    error:
      enabled: true
      channels: ["slack", "email", "teams"]
      escalation_time: 600 # 10 minutes
    critical:
      enabled: true
      channels: ["slack", "email", "teams"]
      escalation_time: 60 # Immediate
      emergency_contacts: ["+251911000000"] # Emergency phone

# Backup and Disaster Recovery Configuration
backup:
  enabled: true
  schedule_cron: "0 2 * * *" # Daily at 2 AM
  retention_days: 90
  max_backups: 30
  compression: true
  encryption: true
  encryption_key: "${BACKUP_ENCRYPTION_KEY}"
  include_logs: true
  include_reports: true
  include_databases: true
  include_config: true
  exclude_patterns:
    - "*.tmp"
    - "*.cache"
    - "node_modules/"
  remote_backup:
    enabled: true
    provider: aws_s3
    bucket: meqenet-governance-backups
    region: eu-west-1
    access_key: "${AWS_ACCESS_KEY_ID}"
    secret_key: "${AWS_SECRET_ACCESS_KEY}"

# Monitoring and Performance Configuration
monitoring:
  enabled: true
  health_check_interval: 300 # 5 minutes
  performance_thresholds:
    max_execution_time: 1800 # 30 minutes
    max_memory_usage: 2048 # 2GB
    max_cpu_usage: 80 # 80%
    max_disk_usage: 85 # 85%
  alerting:
    enabled: true
    cooldown_period: 1800 # 30 minutes between similar alerts
  metrics_retention: 365 # 1 year
  log_retention: 90 # 90 days

# Compliance and Regulatory Configuration
compliance:
  enabled: true
  frameworks:
    nbe: # National Bank of Ethiopia
      enabled: true
      compliance_level: strict
      reporting_frequency: daily
      audit_trail: true
    gdpr: # General Data Protection Regulation
      enabled: true
      data_processing_agreement: true
      privacy_impact_assessment: true
      breach_notification: 72 # hours
    pci_dss: # Payment Card Industry Data Security Standard
      enabled: true
      scope: cardholder_data
      quarterly_scanning: true
      annual_assessment: true
    iso27001: # Information Security Management
      enabled: true
      risk_assessment_frequency: quarterly
      security_awareness_training: monthly
    soc2: # Service Organization Control
      enabled: true
      trust_services_criteria: [security, availability, confidentiality]
      audit_frequency: annual

# Security Configuration
security:
  enabled: true
  encryption:
    data_at_rest: true
    data_in_transit: true
    algorithm: AES256
  access_control:
    role_based_access: true
    multi_factor_authentication: true
    session_timeout: 3600 # 1 hour
  audit_logging:
    enabled: true
    log_level: INFO
    log_retention: 2555 # 7 years (GDPR requirement)
  vulnerability_scanning:
    enabled: true
    frequency: daily
    severity_threshold: medium
    auto_remediation: false

# Ethiopian FinTech Specific Configuration
fintech:
  enabled: true
  currency: ETB
  timezone: "Africa/Addis_Ababa"
  business_hours:
    start: "08:00"
    end: "17:00"
    timezone: "Africa/Addis_Ababa"
    holidays:
      [
        "ethiopian_new_year",
        "orthodox_christmas",
        "timket",
        "orthodox_good_friday",
        "orthodox_easter",
      ]
  regulatory_reporting:
    nbe_monthly: true
    nbe_quarterly: true
    nbe_annual: true
    fayda_id_compliance: true
  payment_methods:
    - mobile_money
    - bank_transfer
    - card_payments
    - digital_wallet

# Dashboard Customization
dashboard:
  theme: enterprise
  colors:
    primary: "#1e40af" # Ethiopian blue
    secondary: "#059669" # Ethiopian green
    warning: "#d97706" # Ethiopian gold
    danger: "#dc2626" # Alert red
    success: "#16a34a" # Success green
  branding:
    company_name: "Meqenet.et"
    logo_path: "assets/logo.png"
    favicon_path: "assets/favicon.ico"
  layout:
    responsive: true
    mobile_optimized: true
    accessibility: wcag_aa

# Integration Configuration
integrations:
  database:
    type: sqlite3
    path: governance/data/
    connection_pool: 10
    timeout: 30
  cache:
    enabled: true
    type: memory
    ttl: 3600 # 1 hour
  api:
    enabled: true
    base_url: "https://api.meqenet.et"
    timeout: 30
    retry_attempts: 3
  external_services:
    threat_intelligence:
      enabled: true
      provider: crowdstrike
      api_key: "${THREAT_INTELLIGENCE_API_KEY}"
    market_data:
      enabled: true
      provider: yahoo_finance
      cache_duration: 300 # 5 minutes

# Advanced Configuration
advanced:
  debug_mode: false
  performance_monitoring: true
  memory_profiling: false
  log_queries: false
  enable_caching: true
  parallel_processing: true
  max_concurrent_dashboards: 3
  request_timeout: 60
  retry_attempts: 3
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 300

# Environment-Specific Configuration
environment:
  production:
    debug_mode: false
    notification_level: warning
    backup_frequency: daily
  staging:
    debug_mode: true
    notification_level: info
    backup_frequency: daily
  development:
    debug_mode: true
    notification_level: debug
    backup_frequency: on_demand

# Version and Metadata
version: "2.0.0"
last_updated: "2025-09-03"
author: "Meqenet.et Governance Team"
description: "Enterprise-grade governance configuration for Ethiopian fintech platform"
compliance_framework: "NBE-GDPR-PCI-DSS-ISO27001-SOC2"
